import React from 'react';
import { Check, HelpCircle } from 'lucide-react';

export const PricingSection: React.FC<{ onGetStarted: () => void }> = ({ onGetStarted }) => {
  const plans = [
    {
      name: 'Starter',
      price: '$0',
      period: 'Forever free',
      desc: 'Ideal for solo local businesses getting their first website live.',
      features: [
        'Unlimited AI copy generations',
        'Homepage & Service copy breakdowns',
        '4x Call-To-Action variations',
        'Live responsive website preview',
        'Instant TXT & Markdown exports',
        'Standard tone adaptation engine',
      ],
      cta: 'Start Free Now',
      popular: false,
    },
    {
      name: 'Pro Unlimited',
      price: '$19',
      period: 'per month',
      desc: 'For growing businesses and studios seeking multi-page copy and PDF exports.',
      features: [
        'Everything in Starter',
        'Formatted PDF website copy downloads',
        'Direct inline copy editing & saving',
        'Advanced neural tone calibration',
        'Saved project storage & history',
        'Custom Gemini API key integration',
        'Priority feature updates',
      ],
      cta: 'Get Pro Access',
      popular: true,
    },
    {
      name: 'Agency Hub',
      price: '$49',
      period: 'per month',
      desc: 'For web designers and agencies managing multiple local business clients.',
      features: [
        'Everything in Pro Unlimited',
        'Multi-client project organization',
        'White-label client presentation mode',
        'Bulk service copy generation',
        'Unlimited exports & team sharing',
        'Dedicated SLA support',
      ],
      cta: 'Scale Your Agency',
      popular: false,
    },
  ];

  const faqs = [
    {
      q: 'Can I use the generated copy on my actual live website?',
      a: 'Yes! All copy generated by LocalLaunch AI is 100% royalty-free and ready to copy-paste directly into WordPress, Webflow, Squarespace, Wix, Shopify, or custom code.',
    },
    {
      q: 'How does LocalLaunch AI prevent generic AI fluff?',
      a: 'Our prompt synthesis engine anchors directly to your specific business type, location, individual services, target audience, and unique selling points without making fake claims.',
    },
    {
      q: 'Does it work for any local business category?',
      a: 'Yes! From salons and clinics to specialty cafes, coaching centers, fitness studios, and local B2B agencies, you can generate customized copy for any local enterprise.',
    },
    {
      q: 'Can I edit the generated copy before exporting?',
      a: 'Yes! You can edit any headline, paragraph, or service description directly inside the dashboard, regenerate individual cards, or export in Markdown, Text, or PDF format.',
    },
  ];

  return (
    <section id="pricing" className="py-20 bg-slate-50/50 dark:bg-slate-900/30 border-t border-slate-200/80 dark:border-slate-800/80">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <span className="text-xs font-bold uppercase tracking-widest text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-950/60 px-3.5 py-1.5 rounded-full border border-indigo-200 dark:border-indigo-800">
            Simple, Transparent Pricing
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white mt-4 mb-4">
            Transform Your Local Business Website Today
          </h2>
          <p className="text-base sm:text-lg text-slate-600 dark:text-slate-300">
            No credit card required. Generate your complete website copy in seconds.
          </p>
        </div>

        {/* Pricing Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-20">
          {plans.map((plan) => (
            <div
              key={plan.name}
              className={`relative bg-white dark:bg-slate-900 rounded-3xl p-8 border flex flex-col justify-between transition-all duration-300 ${
                plan.popular
                  ? 'border-indigo-500 ring-2 ring-indigo-500/20 shadow-2xl shadow-indigo-500/10 md:-translate-y-2'
                  : 'border-slate-200 dark:border-slate-800 shadow-sm hover:shadow-lg'
              }`}
            >
              {plan.popular && (
                <div className="absolute -top-3.5 left-1/2 -translate-x-1/2 px-4 py-1 bg-gradient-to-r from-indigo-600 to-purple-600 text-white text-xs font-extrabold uppercase tracking-wider rounded-full shadow-md">
                  Most Popular
                </div>
              )}

              <div>
                <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2">
                  {plan.name}
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 mb-6 leading-relaxed">
                  {plan.desc}
                </p>

                <div className="flex items-baseline gap-1.5 mb-6 pb-6 border-b border-slate-100 dark:border-slate-800">
                  <span className="text-4xl sm:text-5xl font-extrabold text-slate-900 dark:text-white">
                    {plan.price}
                  </span>
                  <span className="text-xs font-semibold text-slate-400">/{plan.period}</span>
                </div>

                <div className="space-y-3 mb-8">
                  {plan.features.map((feature, idx) => (
                    <div key={idx} className="flex items-start gap-2.5 text-xs sm:text-sm text-slate-700 dark:text-slate-300">
                      <Check className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                      <span>{feature}</span>
                    </div>
                  ))}
                </div>
              </div>

              <button
                onClick={onGetStarted}
                className={`w-full py-3.5 px-4 rounded-xl text-sm font-bold transition-all cursor-pointer ${
                  plan.popular
                    ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-lg shadow-indigo-500/25 hover:shadow-indigo-500/40 hover:-translate-y-0.5'
                    : 'bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200'
                }`}
              >
                {plan.cta}
              </button>
            </div>
          ))}
        </div>

        {/* FAQ Section */}
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-10">
            <h3 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center justify-center gap-2">
              <HelpCircle className="w-6 h-6 text-indigo-500" />
              <span>Frequently Asked Questions</span>
            </h3>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div
                key={idx}
                className="p-5 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm"
              >
                <h4 className="text-base font-bold text-slate-900 dark:text-white mb-2">
                  {faq.q}
                </h4>
                <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
                  {faq.a}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};
